-- File: drizzle/0002_stiff_the_phantom.sql

CREATE TABLE "hexmusic-stream_listening_analytics" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hexmusic-stream_listening_analytics_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"trackId" bigint NOT NULL,
	"trackData" jsonb NOT NULL,
	"sessionId" integer,
	"playedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"duration" integer,
	"totalDuration" integer,
	"completionPercentage" real,
	"skipped" boolean DEFAULT false NOT NULL,
	"playContext" varchar(50),
	"contextId" integer,
	"deviceId" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "hexmusic-stream_playback_state" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hexmusic-stream_playback_state_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"sessionId" integer,
	"currentTrack" jsonb,
	"currentPosition" integer DEFAULT 0,
	"queue" jsonb,
	"history" jsonb,
	"isShuffled" boolean DEFAULT false NOT NULL,
	"repeatMode" varchar(20) DEFAULT 'none' NOT NULL,
	"originalQueueOrder" jsonb,
	"lastUpdated" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hexmusic-stream_player_session" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hexmusic-stream_player_session_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"deviceId" varchar(255) NOT NULL,
	"deviceName" varchar(255),
	"userAgent" text,
	"lastActive" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hexmusic-stream_user_preferences" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hexmusic-stream_user_preferences_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"volume" real DEFAULT 0.7 NOT NULL,
	"playbackRate" real DEFAULT 1 NOT NULL,
	"repeatMode" varchar(20) DEFAULT 'none' NOT NULL,
	"shuffleEnabled" boolean DEFAULT false NOT NULL,
	"equalizerEnabled" boolean DEFAULT false NOT NULL,
	"equalizerPreset" varchar(50) DEFAULT 'Flat',
	"equalizerBands" jsonb,
	"visualizerType" varchar(20) DEFAULT 'bars',
	"visualizerEnabled" boolean DEFAULT true NOT NULL,
	"compactMode" boolean DEFAULT false NOT NULL,
	"theme" varchar(20) DEFAULT 'dark',
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "hexmusic-stream_user_preferences_userId_unique" UNIQUE("userId")
);
--> statement-breakpoint
ALTER TABLE "hexmusic-stream_listening_analytics" ADD CONSTRAINT "hexmusic-stream_listening_analytics_userId_hexmusic-stream_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."hexmusic-stream_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hexmusic-stream_listening_analytics" ADD CONSTRAINT "hexmusic-stream_listening_analytics_sessionId_hexmusic-stream_player_session_id_fk" FOREIGN KEY ("sessionId") REFERENCES "public"."hexmusic-stream_player_session"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hexmusic-stream_playback_state" ADD CONSTRAINT "hexmusic-stream_playback_state_userId_hexmusic-stream_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."hexmusic-stream_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hexmusic-stream_playback_state" ADD CONSTRAINT "hexmusic-stream_playback_state_sessionId_hexmusic-stream_player_session_id_fk" FOREIGN KEY ("sessionId") REFERENCES "public"."hexmusic-stream_player_session"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hexmusic-stream_player_session" ADD CONSTRAINT "hexmusic-stream_player_session_userId_hexmusic-stream_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."hexmusic-stream_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hexmusic-stream_user_preferences" ADD CONSTRAINT "hexmusic-stream_user_preferences_userId_hexmusic-stream_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."hexmusic-stream_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "analytics_user_idx" ON "hexmusic-stream_listening_analytics" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "analytics_track_idx" ON "hexmusic-stream_listening_analytics" USING btree ("trackId");--> statement-breakpoint
CREATE INDEX "analytics_played_idx" ON "hexmusic-stream_listening_analytics" USING btree ("playedAt");--> statement-breakpoint
CREATE INDEX "analytics_session_idx" ON "hexmusic-stream_listening_analytics" USING btree ("sessionId");--> statement-breakpoint
CREATE INDEX "analytics_context_idx" ON "hexmusic-stream_listening_analytics" USING btree ("playContext","contextId");--> statement-breakpoint
CREATE INDEX "analytics_skipped_idx" ON "hexmusic-stream_listening_analytics" USING btree ("skipped");--> statement-breakpoint
CREATE INDEX "playback_user_idx" ON "hexmusic-stream_playback_state" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "playback_session_idx" ON "hexmusic-stream_playback_state" USING btree ("sessionId");--> statement-breakpoint
CREATE INDEX "playback_updated_idx" ON "hexmusic-stream_playback_state" USING btree ("lastUpdated");--> statement-breakpoint
CREATE INDEX "session_user_idx" ON "hexmusic-stream_player_session" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "session_device_idx" ON "hexmusic-stream_player_session" USING btree ("deviceId");--> statement-breakpoint
CREATE INDEX "session_active_idx" ON "hexmusic-stream_player_session" USING btree ("isActive","lastActive");--> statement-breakpoint
CREATE INDEX "session_user_device_idx" ON "hexmusic-stream_player_session" USING btree ("userId","deviceId");--> statement-breakpoint
CREATE INDEX "user_preferences_user_idx" ON "hexmusic-stream_user_preferences" USING btree ("userId");
