-- File: drizzle/0003_chemical_mastermind.sql

CREATE TABLE "hexmusic-stream_audio_features" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hexmusic-stream_audio_features_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"trackId" bigint NOT NULL,
	"bpm" real,
	"key" varchar(10),
	"energy" real,
	"danceability" real,
	"valence" real,
	"acousticness" real,
	"instrumentalness" real,
	"liveness" real,
	"speechiness" real,
	"loudness" real,
	"spectralCentroid" real,
	"analyzedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"source" varchar(50) DEFAULT 'essentia',
	CONSTRAINT "hexmusic-stream_audio_features_trackId_unique" UNIQUE("trackId")
);
--> statement-breakpoint
CREATE TABLE "hexmusic-stream_recommendation_cache" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hexmusic-stream_recommendation_cache_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"seedTrackId" bigint NOT NULL,
	"recommendedTrackIds" jsonb NOT NULL,
	"recommendedTracksData" jsonb NOT NULL,
	"source" varchar(50) DEFAULT 'deezer' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"expiresAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "hexmusic-stream_user_preferences" ADD COLUMN "autoQueueEnabled" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "hexmusic-stream_user_preferences" ADD COLUMN "autoQueueThreshold" integer DEFAULT 3 NOT NULL;--> statement-breakpoint
ALTER TABLE "hexmusic-stream_user_preferences" ADD COLUMN "autoQueueCount" integer DEFAULT 5 NOT NULL;--> statement-breakpoint
ALTER TABLE "hexmusic-stream_user_preferences" ADD COLUMN "smartMixEnabled" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "hexmusic-stream_user_preferences" ADD COLUMN "similarityPreference" varchar(20) DEFAULT 'balanced';--> statement-breakpoint
CREATE INDEX "audio_features_track_idx" ON "hexmusic-stream_audio_features" USING btree ("trackId");--> statement-breakpoint
CREATE INDEX "audio_features_bpm_idx" ON "hexmusic-stream_audio_features" USING btree ("bpm");--> statement-breakpoint
CREATE INDEX "audio_features_energy_idx" ON "hexmusic-stream_audio_features" USING btree ("energy");--> statement-breakpoint
CREATE INDEX "audio_features_key_idx" ON "hexmusic-stream_audio_features" USING btree ("key");--> statement-breakpoint
CREATE INDEX "rec_cache_seed_idx" ON "hexmusic-stream_recommendation_cache" USING btree ("seedTrackId");--> statement-breakpoint
CREATE INDEX "rec_cache_expires_idx" ON "hexmusic-stream_recommendation_cache" USING btree ("expiresAt");--> statement-breakpoint
CREATE INDEX "rec_cache_source_idx" ON "hexmusic-stream_recommendation_cache" USING btree ("source");
